# Generated by Django 3.2.18 on 2023-08-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230811_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('image_source', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='card',
            old_name='cardText',
            new_name='card_text',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='cardTitle',
            new_name='card_title',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='imageSrc',
            new_name='image_source',
        ),
    ]
